### PR TITLE
Simple permission letter

### PR DESCRIPTION
**Pull request by dmarti**
Starting with the basics -- a copy of this would be included with agent
requests.

(Not sufficient for RtD or RtK, just opt outs.)

### CODE REVIEW

**Comment by dmarti** [comment]
Updated letter based on text of a previous permission letter.

**Comment by dazzaji** [comment]
Do you want somebody else to merge the pull request?

**Comment by dmarti** [comment]
@dazzaji Sure, if it looks good to you, or I can do it.

**Comment by dazzaji** [comment]
Happy to.  It's definitely worth versioning up, but a careful scrub will be needed before it goes to production.

**Pull request merged**
